spring:
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testDB
    username: sa
    password:
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        query.in_clause_parameter_padding: true
        show_sql: true
        hbm2ddl:
          auto: create-drop
  web:
    resources:
      add-mappings: false